Repository Medici-Mansion/dreamer, pull requests merged in 2023-11, with the labels that each got.

#4 [CLIENT] image blur처리 및 default image 수정
  .gitignore
  apis/index.ts
  app/(routes)/artisticreference/page.tsx
  app/(routes)/composition/page.tsx
  app/(routes)/layout.tsx
  app/(routes)/style/page.tsx
  app/(routes)/subject/page.tsx
  app/globals.css
  app/layout.tsx
  components/icon-input.tsx
  components/image-card.tsx
  components/nav.tsx
  components/navigation.tsx
  components/prompt.tsx
  components/refresh.tsx
  components/skeleton.tsx
  components/subject-radio.tsx
  components/submit-button.tsx
  components/ui/button.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/skeleton.tsx
  package.json
  public/images/artistic1.png
  public/images/artistic2.png
  public/images/artistic3.png
  public/images/artistic4.png
  public/images/artistic5.png
  public/images/composition1.png
  public/images/composition2.png
  public/images/composition3.png
  public/images/composition4.png
  public/images/composition5.png
  public/images/send.png
  public/images/send_fill.png
  public/images/style1.png
  public/images/style2.png
  public/images/style3.png
  public/images/style4.png
  public/images/style5.png
  store/index.ts
  types/index.ts
  yarn.lock
Labels: 🎨 [CLIENT]

#14 [CLIENT] Welcome 페이지 엔드포인트 변경
  app/(routes)/layout.tsx
  app/(routes)/page.tsx
  app/(routes)/subject/page.tsx
  components/prompt.tsx
Labels: 💡 수정요청, 🎨 [CLIENT]

#13 [CLIENT] API요청 시 로딩상태 추가
  components/icon-input.tsx
  components/subject-radio.tsx
Labels: 💡 수정요청, 🎨 [CLIENT]

#17 [CLIENT} loading 전역 관리 및 disabled 추가
  app/(routes)/page.tsx
  components/icon-input.tsx
  components/nav.tsx
  components/navigation.tsx
  store/loading.ts
  types/index.ts
Labels: 💡 수정요청, 🎨 [CLIENT]

#19 #12 미드저니 api 연동
  app/(routes)/(complete)/generate/layout.tsx
  app/(routes)/(complete)/generate/page.tsx
  app/(routes)/(selection)/artisticreference/page.tsx
  app/(routes)/(selection)/composition/page.tsx
  app/(routes)/(selection)/layout.tsx
  app/(routes)/(selection)/page.tsx
  app/(routes)/(selection)/style/page.tsx
  app/layout.tsx
  components/mj-images.tsx
  components/provider/prompt-provider.tsx
  components/subject-radio.tsx
  lib/hooks/useMj.ts
  lib/paser.ts
  middleware.ts
  next.config.js
  tailwind.config.js
  tailwind.config.ts
Labels: 🔍 QA, 🎨 [CLIENT]

#18 [CLIENT] 선택한 추천 프롬프트 초기화 이슈
  app/(routes)/(complete)/generate/layout.tsx
  app/(routes)/(selection)/artisticreference/page.tsx
  app/(routes)/(selection)/composition/page.tsx
  app/(routes)/(selection)/layout.tsx
  app/(routes)/(selection)/page.tsx
  app/(routes)/(selection)/style/page.tsx
  components/image-card.tsx
  components/prompt.tsx
  components/refresh.tsx
  components/ui/button.tsx
  lib/utils.ts
  store/index.ts
  types/index.ts
Labels: 💡 수정요청, 🎨 [CLIENT]

#23 [CLIENT] artistic 프롬프트 위치 수정 #22
  app/(routes)/(complete)/generate/page.tsx
  app/(routes)/(complete)/layout.tsx
  app/(routes)/(selection)/layout.tsx
  app/(routes)/(subject)/layout.tsx
  components/box-text.tsx
  components/mj-images.tsx
  components/prompt.tsx
  components/provider/auth-provider.tsx
  lib/hooks/useMj.ts
Labels: 🔍 QA, 🎨 [CLIENT]

#26 Hotfix/set prompt block size
  app/(routes)/(complete)/layout.tsx
  store/index.ts
Labels: 🔍 QA, 🎨 [CLIENT]

#29 fix: 프롬프트 완성본 순서 변경
  app/(routes)/(complete)/generate/page.tsx
  components/mj-images.tsx
  components/provider/auth-provider.tsx
  lib/parser.ts
Labels: 🔍 QA, 🎨 [CLIENT]
