Repository Medici-Mansion/dreamer, pull requests merged in 2024-01, with the labels that each got.

#36 [CLIENT] 캐러셀, 중복선택 해제 추가
  app/(routes)/(complete)/generate/page.tsx
  app/(routes)/(complete)/layout.tsx
  app/(routes)/(selection)/artisticreference/page.tsx
  app/(routes)/(selection)/composition/page.tsx
  app/(routes)/(selection)/layout.tsx
  app/(routes)/(selection)/mood/page.tsx
  app/(routes)/(selection)/style/page.tsx
  app/(routes)/(selection)/tone/page.tsx
  app/(routes)/(subject)/page.tsx
  app/globals.css
  components/box-text.tsx
  components/icon-input.tsx
  components/image-card.tsx
  components/nav.tsx
  components/prompt.tsx
  components/provider/auth-provider.tsx
  components/subject-radio.tsx
  components/ui/carousel.tsx
  components/ui/input.tsx
  lib/utils.ts
  store/index.ts
  tailwind.config.ts
  types/index.ts
Labels: ✅ 완료, 🎨 [CLIENT]

#38 [CLIENT] 카테고리 중복 선택 시 프롬프트 생성 추가
  app/(routes)/(complete)/generate/page.tsx
  app/(routes)/(complete)/layout.tsx
  app/(routes)/(selection)/artisticreference/page.tsx
  app/(routes)/(selection)/composition/page.tsx
  app/(routes)/(selection)/layout.tsx
  app/(routes)/(selection)/mood/page.tsx
  app/(routes)/(selection)/style/page.tsx
  app/(routes)/(selection)/tone/page.tsx
  components/box-text.tsx
  components/icon-input.tsx
  components/image-card.tsx
  components/mj-images.tsx
  components/next-buttons.tsx
  components/prompt.tsx
  components/submit-button.tsx
  components/ui/button.tsx
  components/ui/carousel.tsx
  lib/parser.ts
  store/index.ts
  tailwind.config.ts
Labels: 🔍 QA, 🎨 [CLIENT]

#37 [CLIENT] 캐러셀 화살표 스타일 변경
  components/ui/carousel.tsx
Labels: ✅ 완료, 🎨 [CLIENT]

#39 [CLIENT] 네비게이션 체크
  app/(routes)/(subject)/page.tsx
  app/layout.tsx
  components/box-text.tsx
  components/nav.tsx
  components/navigation.tsx
  constants.ts
  fonts.ts
  types/index.ts
Labels: ✅ 완료, 🎨 [CLIENT]

#42 [Feature][CLIENT] 수정 요청사항 적용
  app/(routes)/(selection)/artisticreference/page.tsx
  app/(routes)/(selection)/composition/page.tsx
  app/(routes)/(selection)/mood/page.tsx
  app/(routes)/(selection)/style/page.tsx
  app/(routes)/(selection)/tone/page.tsx
  app/(routes)/(subject)/page.tsx
  app/globals.css
  components/box-text.tsx
  components/icon-input.tsx
  components/image-card.tsx
  components/next-buttons.tsx
  components/prompt.tsx
  components/subject-radio.tsx
  components/ui/carousel.tsx
  tailwind.config.ts
Labels: 🔍 QA, 💡 수정요청, ✅ 완료, 🎨 [CLIENT]

#44 [Feature][CLIENT] 추가 수정사항 적용
  components/box-text.tsx
  components/next-buttons.tsx
  components/prompt.tsx
Labels: 🔍 QA, 🎨 [CLIENT]
